{% set version = "1.1.01" %}
package:
    name: pydatpicture
    version: {{ version }}

source:
  git_url: https://github.com/allenea/PyDatPicture.git
  
  
requirements:
    build:
        - python 3.*
        - numpy
        - scipy
        - matplotlib
        - pandas
        - cartopy
        - geographiclib
        - geopy


    run:
        - python 3.*
        - numpy
        - scipy
        - matplotlib
        - pandas
        - cartopy
        - geopy
     
about:
  home: https://github.com/allenea/PyDatPicture
  license: GNU General Public License v3.0
  summary: 'Getting geolocation from photos on your computer as usable data.'
  description: |
    Do you like to travel and take pictures? Now you can track where you've been using pyDatPicture.
    This module analyzes pictures/videos to identify geolocation data returning a list of times, latitude, and longitudes that can then be mapped in python or GIS.
  dev_url: https://github.com/allenea/PyDatPicture
  doc_url: https://github.com/allenea/PyDatPicture/blob/master/README.md
  doc_source_url: https://github.com/allenea/PyDatPicture/blob/master/README.md
  
  